### PR TITLE
Added download button for event attendance table

### PR DESCRIPTION
**Pull request by andrewzpu**
Added button at the bottom of the event detail page to download the attendance table

Note: I excluded columns with buttons ("Check Off" and "Edit Points")

### CODE REVIEW

**Review by ryanyychen — CHANGES_REQUESTED** [review]
Looks good! Can you include emails?

**Comment by andrewzpu** [comment]
> Looks good! Can you include emails?

The download csv button looks at the html data to create the csv, so I just changed the Event Console to include the attendees's emails in the table. Is this ok? Or would you rather only include email in the csv and not the table?

**Comment by ryanyychen** [comment]
> > Looks good! Can you include emails?
> 
> The download csv button looks at the html data to create the csv, so I just changed the Event Console to include the attendees's emails in the table. Is this ok? Or would you rather only include email in the csv and not the table?

Yeah, let's not clutter the table by including email in the table. Can you have it only include email in the csv?

**Comment by andrewzpu** [comment]
> > > Looks good! Can you include emails?
> > 
> > 
> > The download csv button looks at the html data to create the csv, so I just changed the Event Console to include the attendees's emails in the table. Is this ok? Or would you rather only include email in the csv and not the table?
> 
> Yeah, let's not clutter the table by including emails. Can you have it only include email in the csv?

Ok, I changed it so that email is now a hidden column at the end of the table, so it won't display but it will be included in the csv as the last column

**Review by ryanyychen — APPROVED** [review]

**Pull request merged**
